import { Kumbh_Sans, DM_Mono } from "next/font/google";
import "./lib/globals.css";
import styles from "./page.module.css";
import Navigation from "./ui/navigation/navigation";
import EmailLink from "./ui/emailLink/emailLink";
import Title from "./ui/title/title";
import Footer from "./ui/footer/footer";
import About from "./about/page";
import Projects from "./projects/page";
import Experience from "./experience/page";

const kumbh = Kumbh_Sans({ subsets: ["latin"], weight: "400" });
const mono = DM_Mono({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Jacques Portfolio",
  description: "Generated by Jacques",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kumbh.className}>
        <div className={styles.main__Wrapper}>
          <div className={styles.main__Left}>
            <Title />
            <Navigation />
            <EmailLink />
            <Footer />
          </div>
          <div className={`${styles.main__Right} ${styles.main__RightDesktop}`}>
          
            {children}
          </div>
          <div className={`${styles.main__Right} ${styles.main__RightMobile}`}>
            <About /> <Projects /> <Experience />
          </div>
        </div>
      </body>
    </html>
  );
}
